language: node_js

node_js:
    - "node"
    - "12"

git:
    submodules: false

before_script:
    - npm install
    - npm start
    - npm test

after_success:
    - npm run report-coveralls
    - npm run report-codecov
