language: node_js

node_js:
    - "node"
    - "12"
    - "10"
    - "14"

git:
    submodules: false

before_script:
    - npm install -g forever

script:
    - forever start -c 'npm start' ./
    - npm test

after_script:
    - forever stopall
