language: node_js

node_js:
    - "node"
    - "12"
    - "11"
    - "10"
    - "14"
    - "13"

git:
    submodules: false

before_script:
    - npm install
    - npm run

script:
    - npm test

after_success:
    - npm run report-coveralls
    - npm run report-codecov
