language: node_js

node_js:
    - "node"
    - "12"
    - "11"
    - "10"
    - "14"
    - "13"

git:
    submodules: false

addons:
    firefox: "68.1"

before_install:
    - wget https://github.com/mozilla/geckodriver/releases/download/v0.25.0/geckodriver-v0.25.0-linux64.tar.gz
    - mkdir geckodriver
    - tar -xzf geckodriver-v0.25.0-linux64.tar.gz -C geckodriver
    - export PATH=$PATH:$PWD/geckodriver


before_script:
    - npm install

script:
    - npm test

# after_success:
#     - npm run report-coveralls
#     - npm run report-codecov
